### ISSUE TITLE
Future Development and Features Roadmap

### ISSUE THREAD

**Issue by solvingj** [nessos/Eff#1]
This looks really nice actually.  I'm new to using Effects, but have studied it extensively in the past few months.  Do you have plans to extend it further?  I will be experimenting with this in a project soon, and if I'm going to extend it, I'd like to work on features that you've already thought of.

**Comment by palladin** [comment]
I don't have any plans for future development but I would love ti see how Eff can be used in a practical setting.

**Comment by solvingj** [comment]
My last project was largely written using this other functional library: 
https://github.com/vkhorikov/CSharpFunctionalExtensions/

I will probably use it on this new project as well, and try to figure out if/how the two can be used together.

**Comment by solvingj** [comment]
For posterity, in Eric Torreborre's talk about using Eff monad in Scala, he provides library implementation of what is very likely to be the first few practical monads bulit on top of Eff:
https://youtu.be/KGJLeHhsZBo?t=1606

Here are the effects included: 

|Monad | description|
|----------|------------|
|EvalEffect | an effect for delayed computations
|OptionEffect | an effect for optional computations, stopping when there’s no available value\
|EitherEffect | an effect for computations with failures, stopping when there is a failure
|ValidateEffect | an effect for computations with failures, allowing to collect failures
|ErrorEffect | a mix of Eval and Either, catching exceptions and returning them as failures
|ReaderEffect | an effect for depending on a configuration or an environment
|WriterEffect | an effect to log messages
|StateEffect | an effect to pass state around
|ListEffect | an effect for computations returning several values
|ChooseEffect | an effect for modeling non-determinism
|MemoEffect | an effect for memoizing values
|FutureEffect | an effect for asynchronous computations 
|SafeEffect | an effect for guaranteeing resource safety 

http://atnos-org.github.io/eff/org.atnos.site.OutOfTheBox.html

**Comment by solvingj** [comment]
Given the above, it's possible that there are the most opportunities for using this implementation of Eff into the `language-ext` library.  

https://github.com/louthy/language-ext

Assuming basic compatibility/compose-ability between your Eff type and the types in that library, I can see a very simple step forward in bringing both libraries together and trying to mimic the above Effect types.

**Comment by palladin** [comment]
I'm not familiar with language-ext but I agree that it needs maturity and proof of value.

**Comment by solvingj** [comment]
If you have time to look language-ext over, i would like to know your thoughts.

**Comment by solvingj** [comment]
My question has been answered.  The library currently appears to be a complete implementation of Eff which is ready for general use.
