### ISSUE TITLE
Question: Handle some effects but not all

### ISSUE THREAD

**Issue by bent-rasmussen** [nessos/Eff#25]
Pardon me if this question is naive: is it possible to handle one effect and ignore another? As an example, it is quite common with exceptions to handle some exception close to the target site and let others bubble up the call stack to handle at a higher level. So it would seem similarly useful to be able to "catch", i.e. handle, some effects and let others pass through.

**Comment by palladin** [comment]
One possible approach is something like 
```
public class CombinedDateTimeConsoleEffectHandler : EffectHandler
{
    private readonly EffectHandler[] _nestedHandlers = new EffectHandler[]
    {
        new ConsoleEffectHandler(),
        new DateTimeEffectHandler(),
    };
 
    public override async ValueTask Handle<TResult>(EffectAwaiter<TResult> awaiter)
    {
        foreach (EffectHandler handler in _nestedHandlers)
        {
            await handler.Handle(awaiter);
            if (awaiter.IsCompleted)
            {
                return;
            }
        }
    }
}
 
Test().Run(new CombinedDateTimeConsoleEffectHandler());
```
Read @eiriktsarpalis's blog post for more details.

**Comment by bent-rasmussen** [comment]
Thank you for the reply. I was thinking more along the lines of this though:

```csharp
async Task Main()
{
	await Test1().Run(new RandomCoinTossHandler()); // handle WriteLine
}

async Eff Test1()
{
	await Test2().Run(new WriteLineHandler());
}

async Eff Test2()
{
	var handler = new RandomCoinTossHandler(); // handle CoinToss and let WriteLine escape
	await Test3().Run(handler);
}

async Eff Test3()
{
	var cointoss = await new CoinToss();
	await new WriteLine(cointoss ? "Head" : "Tail"); // InvalidOperationException: Awaiter of type WriteLine has not been completed
}
```

I do not want to take up more of your time though. I will experiment.

Thank you for making this awesome library! :-)

**Comment by eiriktsarpalis** [comment]
Right, so I suppose the question is you are looking to somehow scope additional effects in a particular method call? It's not currently possible, as you probably already found out the new effect handler completely replaces the original one. 

In principle though, it should be possible to create an effect that returns the current effect handler:
```csharp
public GetCurrentHandlerEffect : Effect<IEffectHandler>
{

}

Eff Test2()
{
     IEffectHandler currentHandler = await new GetCurrentHandlerEffect();
     await Test3().Run(new CombinedHandler(currentHandler, new RandomCoinTossHandler()));
}
```

**Comment by bent-rasmussen** [comment]
Your technique looks promising! Perhaps one can use stack semantics as well:

```csharp
async Eff Test2()
{
	await new PushEffectHandler(new RandomCoinTossHandler());
	await Test3();
	await new PopEffectHandler();
}
```

So these techniques should provide for handling scoped effects. Then there is the question of having effects within an effect handler (this kind of simulates that) and having pipeline composition of effect handlers, e.g. for effects that return values.

My question has been answered. I will follow your blog with enthusiasm. :-)

**Comment by eiriktsarpalis** [comment]
That's certainly another way. There's a lot of approaches that could be followed, though the library is intentionally not exposing any to minimize conceptual overload.
