### ISSUE TITLE
Recommended way for effect transformation

### ISSUE THREAD

**Issue by Tyrrrz** [nessos/Eff#26]
Hi!

I looked into the samples and have been left wondering about something. Is there a core/recommended way to facilitate mapping of one effect to another?

The idea is to be able to perform something like this:

```csharp
await new CoinToss().Map(result ? "Heads" : "Tails");
```

**Comment by eiriktsarpalis** [comment]
I would recommend just using a var after the await:
```csharp
bool result = await new CoinToss();
var mappedResult = result ? "Heads" : "Tails";
```

While you could in principle write a "Map" effect, it will generally result in more complexity in the effect handler.

**Comment by Tyrrrz** [comment]
Thanks!
