### ISSUE TITLE
Better looking dependency injection?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nessos/Eff#28]
I see next
```
 if (await IO<IUserService>.Do(svc => svc.CreateUser(newUserName, password)))
```

Anyways to improve? I think of:
1. inject dependencies via async locals in static classes. So may be (await IO()).CreateUser` or like to look less alient?
2. use fluent combinatorics interfaces so that delegates are Ok. Examples
```
        public async Task DeallocatedStop(ushort poolId, DistributedLock mutex) {
           await settings_
                .GetSettings()
                .ToAsync(poolId, GetServersForDeallocation)
                .TapAsync(mutex.Lease)
                .ToAsync(DeallocateStopServers);
        }
```
If I will port it to Eff tasks than Do will look in place (actually I want to call mutex.Lease and logger automatically). I have (part is here https://gist.github.com/dzmitry-lahoda/78bd89c3aa804aa0467dcba0a2e1defd#file-system-threading-tasks-funextensions-cs) combinators for Tasks, could do same for Eff and see how it looks. I was able imitate partial application with fluent combinators either.
3. Use https://github.com/dadhi/SharpIO or LanguageExt to write interpreters via LINQ DSL.

Other ideas or suggestions to try?

**Comment by palladin** [comment]
I'm not sure that I get your question... but I'll give it a try
IO.Do is a simple to use lambda-wrapping mechanism for effects.
You can always declare your own effects 
example https://github.com/nessos/Eff/blob/master/samples/Eff.Examples.Console/ConsoleEffect.cs

**Comment by dzmitry-lahoda** [comment]
```csharp
// i dislike this
await IO<IUserService>.Do(svc => svc.CreateUser(newUserName, password));

// i like more this
await IO<IUserService>.CreateUser(newUserName, password);// is this possible?
await IO<IUserService>().CreateUser(newUserName, password)); // is this possible?
await UserEffect.CreateUser(newUserName, password); //  `UserEffectHandler` created via DI (and other handlers)
```

if to consider full program than `Do` may be fine:
```
await IO<IUserService>.Do(svc => svc.CreateUser(newUserName, password)).To(NextStep).OrElse(Bad); 
await IO<IUserSerive, ILogger>.Do((svc, logger) => ... ) ; // up to 16 generics params? but that does not support named or tagged resolutions
```

I am trying imaging writing real program with `effects` in production (read my PRs should be accepted). And thinking what is best way to express these.

**Comment by palladin** [comment]
``` await UserEffect.CreateUser(newUserName, password); ``` is certainly possible, check the samples.

**Comment by dzmitry-lahoda** [comment]
this leads me to the idea that instead of interface DI samples could(should) show example with 2 different effect handlers injected with stuff from DI and it will look more idiomatic/clean/systematic. that is what i want to try. i guess can simplify writing (sugar/shortucts) DI enabled effects.

**Comment by eiriktsarpalis** [comment]
The `IO.Do()` methods provide a simple mechanism for quickly converting OOP-based DI to Effect-based DI. As mentioned this doesn't preclude using a more idiomatic style, however
```csharp
await IO<IUserService>.CreateUser(newUserName, password);// is this possible?
await IO<IUserService>().CreateUser(newUserName, password)); // is this possible?
```
The first case is not allowed because it would never type check and the latter case, while possible, actually uses effects to resolve `IUserService`, however the effect of "CreateUser" is executed via regular async/await semantics and therefore not managed by a handler. We want to avoid encouraging the latter style.
