### ISSUE TITLE
Question about the example EffectHandler in README.md

### ISSUE THREAD

**Issue by jpierson** [nessos/Eff#3]
What is the purpose of returning the type ValueTask<ValueTuple> from Handle in the main example from [README.md](https://github.com/nessos/Eff/blame/master/README.md#L21). Additionally this method is async but doesn't await anything awaitable, is this intentional as it seems that the async keyword could just be omitted in the example?

**Comment by palladin** [comment]
Actually, the correct type of Handle is 
``Handle<T> : IEffect<T> -> Task``
and the reason is that we need to compose it with  Run 
``Run<T> : IEffectHandler -> Task<T>``
Of course we can define our own Run and Handlers.

**Comment by jpierson** [comment]
I tried getting the example in the Readme.md file working in LinqPad to play around with more to see if I could make sense out of your explanation above but unfortunately I'm hitting the following error.

> CS0117 'Effect' does not contain a definition for 'Random'

http://share.linqpad.net/qrh376.linq

Glancing through the source code I haven't spotted a method called Random on Effect that would allow this example to compile as is. My guess is that I'm overlooking something.

**Comment by palladin** [comment]
The example is not complete, is only for demonstration purposes.

**Comment by solvingj** [comment]
Note that the RandomEffect in the readme example comes from the following example project in the solution. 

https://github.com/nessos/Eff/blob/0233d59dd3ca9f62050096dc77224e5f804f1261/src/examples/Eff.Examples.RecordReplay/RecordEffectHandler.cs

I believe RandomEffect is an example of a user-defined Effect. Is that correct @palladin ?

**Comment by palladin** [comment]
Yes!
