### ISSUE TITLE
IEffect interface with default implementation (.NET standard 2.1)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nessos/Eff#30]
I believe next is possible if to have IEffect(same as Effect) with implementation:
```

    public struct ConsoleReadEffect : IEffect<ConsoleReadEffect , string>
    {
    }

    public static class ConsoleEffect
    {
        public static ConsoleReadEffect Read() => default;
    }
```

So stateless effects can be modeled as as structs.

**Comment by dzmitry-lahoda** [comment]
It will break implicit cast, but as per docs it can be removed with C# covariant returns (which are in 9) as I see

**Comment by eiriktsarpalis** [comment]
While DIMs are certainly applicable for many constructs in Eff, I would err towards not adding them as it introduces a hard dependency on .NET Core > 3 runtimes.
